# From: https://github.com/marketplace/actions/assign-pr-to-author
name: Assign Author to PR
on: [pull_request]

jobs:
  assignAuthor:
    runs-on: ubuntu-latest
    name: Assign Author to PR
    steps:
      - uses: samspills/assign-pr-to-author@v1.0
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'