name: markdownlint

on: [pull_request]

jobs:
  delivery:

    runs-on: ubuntu-latest
    name: Linting Markdown

    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - name: Lint Code Base
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: "**/*.md -i themes"
