name: cspell

on:
  push:
    branches:
      - **
  pull_request:
    branches:
      - main # only runs on PRs on main branch

jobs:
  spellchecking:
    runs-on: ubuntu-latest
    name: Linting Markdown
    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - uses: actions/setup-node@v1
        name: Run spell check
        with:
          node-version: "12"
      - run: npm install -g cspell
      - run: cspell --config ./cSpell.json "**/*.md"