# From: https://github.com/marketplace/actions/contribute-list
name: Update Readme Contributors

on: [pull_request]

jobs:
    contrib-readme-job:
        runs-on: ubuntu-latest
        name: Add contributors to README.md
        steps:
            - name: Contribute List
              uses: akhilmhdh/contributors-readme-action@v2.1.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# Add this to the README file:
# <!-- readme: contributors -start -->
# <!-- readme: contributors -end -->