name: Copy
on: push
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: markcheret/copycat-action@v3.2.4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: "."
        dst_path: "/.github/workflows/"
        dst_owner: markcheret
        dst_repo_name: cheret-de
        dst_branch: main
        src_branch: main
        file_filter: "*.yml"
        exclude: ".github/workflows/*.yml"