name: distribute markdownlint
on: push
jobs:
  copy-cheret-de:
    runs-on: ubuntu-latest
    steps:
    - name: copy markdownlint to cheret-de
      uses: andstor/copycat-action@v3.2.4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: "."
        dst_path: "/."
        dst_owner: markcheret
        dst_repo_name: cheret-de
        dst_branch: main
        src_branch: main
        file_filter: "*.markdownlint"
  copy-cheret-org:
    runs-on: ubuntu-latest
    steps:
    - name: copy markdownlint to cheret-org
      uses: andstor/copycat-action@v3.2.4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: "."
        dst_path: "/."
        dst_owner: markcheret
        dst_repo_name: cheret-org
        dst_branch: main
        src_branch: main
        file_filter: "*.markdownlint"
  copy-cheret-tech:
    runs-on: ubuntu-latest
    steps:
    - name: copy markdownlint to cheret-tech
      uses: andstor/copycat-action@v3.2.4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: "."
        dst_path: "/."
        dst_owner: markcheret
        dst_repo_name: cheret-tech
        dst_branch: main
        src_branch: main
        file_filter: "*.markdownlint"
  copy-popcornscience:
    runs-on: ubuntu-latest
    steps:
    - name: copy markdownlint to cheret-tech
      uses: andstor/copycat-action@v3.2.4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: "."
        dst_path: "/."
        dst_owner: markcheret
        dst_repo_name: popcornscience
        dst_branch: main
        src_branch: main
        file_filter: "*.markdownlint"