name: distribute issue-templates
on: push
jobs:
  copy-cheret-de:
    runs-on: ubuntu-latest
    steps:
    - name: copy issue-templates to cheret-de
      uses: markcheret/copycat-action@v3.2.4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: "./.github/ISSUE_TEMPLATE/"
        dst_path: "/.github/ISSUE_TEMPLATE/"
        dst_owner: markcheret
        dst_repo_name: cheret-de
        dst_branch: main
        src_branch: main
        file_filter: "*.md"
  copy-cheret-org:
    runs-on: ubuntu-latest
    steps:
    - name: copy issue-templates to cheret-org
      uses: markcheret/copycat-action@v3.2.4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: "./.github/ISSUE_TEMPLATE/"
        dst_path: "/.github/ISSUE_TEMPLATE/"
        dst_owner: markcheret
        dst_repo_name: cheret-org
        dst_branch: main
        src_branch: main
        file_filter: "*.md"
  copy-cheret-tech:
    runs-on: ubuntu-latest
    steps:
    - name: copy issue-templates to cheret-tech
      uses: markcheret/copycat-action@v3.2.4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: "./.github/ISSUE_TEMPLATE/"
        dst_path: "/.github/ISSUE_TEMPLATE/"
        dst_owner: markcheret
        dst_repo_name: cheret-tech
        dst_branch: main
        src_branch: main
        file_filter: "*.md"